### ISSUE TITLE
Use novnc with `network_mode: host`

### ISSUE THREAD

**Issue by ShevaDavid** [theasp/docker-novnc#9]
If I set 
`network_mode: host`
in docker-compose file, the http://localhost:8080/vnc.html does not work anymore 
here is my setup
```
version: '2'
services:
  ide:
    image: psharkey/intellij:latest
    network_mode: host
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
  novnc:
    image: theasp/novnc:latest
    network_mode: host
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
```

**Comment by foundway** [comment]
Any solution to this? I am trying to use host network and encountered the same issue.

**Comment by tony2guo** [comment]
Workaround: share the Xvfb Unix socket via a named volume

Instead of relying on Docker DNS (which isn't available to `network_mode: host` containers), share the X11 Unix socket directly between containers:

```yaml
volumes:
  x11:

services:
  novnc:
    image: theasp/novnc:latest
    volumes:
      - x11:/tmp/.X11-unix
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no

  app:
    network_mode: host
    volumes:
      - x11:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
```

The `novnc` container starts Xvfb and creates `/tmp/.X11-unix/X0` inside the `x11` volume. The `app` container connects to it via `DISPLAY=:0` through the `x11` volume.
